### ISSUE TITLE
Source code ?

### ISSUE THREAD

**Issue by 1995parham** [bambil/bambil.github.io#1]
Where is this static directory come from ? have you removed source code from this repository ?

**Comment by Tabrizian** [comment]
No source code is inside the ```src``` branch. Unfortunately GitHub organization gh-pages depends on master branch :(

**Comment by 1995parham** [comment]
I've got it 🙌 so I changed default branch to `src`.

**Comment by Tabrizian** [comment]
Perfect :raised_hands:
