### ISSUE TITLE
Invalid GitHub / Twitter links

### ISSUE THREAD

**Issue by WyldePointer** [bambil/bambil.github.io#2]
The following links / URLs are not valid and resulting in a GitHub's 404 page instead:

https://bambil.github.io/@Tabrizian
https://bambil.github.io/_iman96_

https://bambil.github.io/@1995parham
https://bambil.github.io/@1995parham

**Comment by Tabrizian** [comment]
You're right. I'll fix it as soon as possible.

**Comment by 1995parham** [comment]
Done 😄 Thanks for reporting this to us @WyldePointer

**Comment by WyldePointer** [comment]
@1995parham Cool! You're welcome.
